#!/usr/bin/env python3

import sys
import json

for line in sys.stdin:
    doc = json.loads(line)
    if "title" in doc:
        print(doc["title"])
    if "section_texts" in doc:
        print(*doc["section_texts"], sep="\n")
